name: Build and Test ICU4C with Zig

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-library-linux:
    name: Build (Linux x86-64 + Arm-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Run on x86-64
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y \
              bash        \
              curl        \
              file        \
              jq          \
              less        \
              man         \
              manpages    \
              nano        \
              python3     \
              python3-pip \
              sudo        \
              tree        \
              unzip       \
              wget        \
              xmlstarlet  \
              zip

            echo "Yo!"
            pwd
            ls -la
            chmod +x *.sh
            echo 
            echo "./init-setup.sh"
            ./init-setup.sh
            echo 
            echo "tree -L 3 build"
            tree -L 3 build
            echo 
            echo "./build.sh $(pwd)"
            ./build.sh $(pwd)

            echo 
            echo "tree -L 3 build/icu4c-target"
            tree -L 3 build/icu4c-target

            echo 
            echo "./package.sh $(pwd)"
            ./package.sh $(pwd)

            echo 
            echo "tree -L 3 dist/icu4c-library"
            tree -L 3 dist/icu4c-library

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: icu4c-library
          path: dist/icu4c-library
          if-no-files-found: error
          retention-days: 1
