name: Build and Test ICU4C with Zig

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-library:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Setup
        run: |
            sudo apt-get update -qq
            sudo apt-get install -y \
              bash        \
              curl        \
              file        \
              jq          \
              less        \
              man         \
              manpages    \
              nano        \
              python3     \
              python3-pip \
              sudo        \
              tree        \
              unzip       \
              wget        \
              xmlstarlet  \
              zip

            chmod +x *.sh
            echo 
            echo "./init-setup.sh"
            ./init-setup.sh

      - name: Inspace build
        run: |
            tree -L 3 build

      - name: Build the library
        run: |
            echo "./build.sh $(pwd)"
            ./build.sh $(pwd)

      - name: Inspace target
        run: |
            echo "tree -L 3 build/icu4c-target"
            tree -L 3 build/icu4c-target

      - name: Package
        run: |
            echo "./package.sh $(pwd)"
            ./package.sh $(pwd)

      - name: Inspect dist
        run: |
            echo "tree -L 3 dist/icu4c-library"
            tree -L 3 dist/icu4c-library

      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: icu4c-library
          path: dist/icu4c-library
          if-no-files-found: error
          retention-days: 1

  # Build Test
  build-test-:
    name: Build Test
    needs: build-library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: icu4c-library
          path: dist

      - name: Show tree
        run: tree

      - name: Show tree dist
        run: tree dist

      - name: Run on x86-64
        run: |
          pushd tests

          chmod +x *.sh
          ls -la 
          tree

          popd
          