name: Build and Test ICU4C with Zig

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build-library-linux:
    name: Build (Linux x86-64 + Arm-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set non-interactive frontend
        run: echo 'DEBIAN_FRONTEND=noninteractive' >> $GITHUB_ENV

      - name: Run on x86-64
        run: |
            echo "Yo!"
            pwd
            ls -la
            chmod +x *.sh
            echo 
            echo "./ensure-linux-x86-64-build-environment.sh"
            ./ensure-linux-x86-64-build-environment.sh
            echo 
            echo "./install-zig.sh"
            ./install-zig.sh
            echo 
            echo "./prepare-icu4c-source.sh"
            ./prepare-icu4c-source.sh
            echo 
            echo "./build.sh"
            ./build.sh
